# Generated by Django 4.2.4 on 2024-05-04 16:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_color_variant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="category_image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="color_variant",
        ),
        migrations.RemoveField(
            model_name="product",
            name="size_variant",
        ),
        migrations.DeleteModel(
            name="ColorVariant",
        ),
        migrations.DeleteModel(
            name="SizeVariant",
        ),
    ]
